paths:
  background: 
    'paint': 'src/reincarnator/assets/backgrounds/set_0'
  foreground: 
    'car': 'src/reincarnator/assets/foregrounds/images/car'
  output: 'src/reincarnator/outputs/'
params:
  alpha_max: 1 
  alpha_min: 0.8
  boundary_threshold: 32
  instance_count_min: 1
  instance_count_max: 1
  occlusion_threshold: 0.7
  output_count: 20000
  size_ratio_upper: 0.618
  target_width: 1024
  target_height: 1024