# Template of config.yml, omit the `.template` suffix before use.
blender-path: ""                        # Use blender.exe if there is one.
paths:
  addon-folder: "src/fragmentor/assets/addons/"
  addons:
    - "PSA-1.81-addon-EN.zip"
  blend-folder: "src/fragmentor/assets/"     # Assign folder where models are stored.
  model-folder: "src/fragmentor/assets/models/"            # Model folder is relative path under blend folder
  foreground:
    "car": "car"
    # "mid-size-truck": "mid-size-truck"
    # "truck": "truck"
    # "van": "van"
  output: 'src/fragmentor/outputs/'
params:
  cam:
    rotx_max: 90
    rotx_min: 75
names:
  model-collection: "model"
  camera: 'Camera'
  sun: 'Starlight Sun'
  bbx3d: 'bounding_box'
experiments:
  name: "demo-experiment"
  count: 20000
  seed: 114514
logger:
  monitor:
    interval: 1
  console: 
    verbose-level: 0
    max-count: 500
