# Template of config.yml, omit the `.template` suffix before use.
blender-path: ""                        # Use blender.exe if there is one.
paths:
  addon-folder: "src/fragmentor/assets/addons/"
  addons:
    - "PSA-1.81-addon-EN.zip"
  blend-folder: "src/fragmentor/assets/"     # Assign folder where models are stored.
  model-folder: "models/"            # Model folder is relative path under blend folder
  image-output: "src/fragmentor/outputs/"
  label-output: "src/fragmentor/outputs/"
names:
  model-collection: "model"
  camera: 'Camera'
  sun: 'Starlight Sun'
experiments:
  name: "demo-experiment"
  count: 20000
  seed: 114514
logger:
  monitor:
    interval: 1
  console: 
    verbose-level: 0
    max-count: 500
